# Travis-CI Build for dynamitey 
# see travis-ci.org for details

language: csharp
os:
  - linux
  - osx

env:
  - SLN=TCP.NET652.sln
    TARGET=NET652
    VERSION=Release

install:
   - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
   - mono nuget.exe install NUnit.Runners -Version 3.5.0 -OutputDirectory testrunner

script:
  - ./build.sh
