image: Visual Studio 2017

install:
    appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

before_build:
    nuget restore TCP.Net462.sln

build:
    project: TCP.Net462.sln
